collections:
  people:
  talks:
  seminars:

plugins: ['jekyll/scholar']

scholar:
  style:  apa
  bibliography_template: bib
  replace_strings: true
  repository: assets/papers
  source: _bibliography
  bibliography: references.bib

sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-autoprefixer
  - jekyll-scholar